---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-arka-project
  labels:

    ecommerce-arka-project.io/name: ecommerce-arka-project
    app.kubernetes.io/instance: ecommerce-arka-project
    app.kubernetes.io/name: ecommerce-arka-project
    app.kubernetes.io/version: "1.12.0"
    app.kubernetes.io/part-of: ecommerce-arka-project
